### ISSUE TITLE
Y axis graph for Tomas' Formula seems to be broken due to "min: processCombinedChartData().minValue - 10000" 

### ISSUE THREAD

**Issue by HishamLadha** [fiji-solutions/tlx-dashboard#1]
Description:
- In TGA1.js, line 1720 `min: processCombinedChartData().minValue - 10000` seems to not work properly due to the large numbers being used in Tomas' Chart. 
<img width="1511" alt="Screenshot 2024-08-10 at 3 22 35 PM" src="https://github.com/user-attachments/assets/b7c9197d-5e2c-45e6-ba21-735d737253ba">

**Comment by HishamLadha** [comment]
This seems to be a temporary fix. @cmoutafidis is there a way to eliminate the starting value which seems to always be 0? It seems to be messing up the graph scaling. 
<img width="733" alt="image" src="https://github.com/user-attachments/assets/1cfbc4f9-23ae-4823-b287-2a147c50f0d9">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/da87551e-53ff-4f28-950d-ceb16d150d75">

**Comment by HishamLadha** [comment]
Found a better fix: 

1. On line 1602 of TGA.js, change it to `const validCombinedData = combinedData.filter(
            (value) => value !== null && value >= 0
          );`
This fixes the issue of validCombinedData always having a negative as minValue impacting the y-axis scale.
2. Change the input of the chart to take in validCombinedData as the value for `data:`. See below: 
<img width="655" alt="image" src="https://github.com/user-attachments/assets/8854c239-5f7d-4438-a807-03a721e985fa">

Now looks like this: 
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e25f455a-e700-4290-a1dc-7ec8f2efea7b">

**Comment by cmoutafidis** [comment]
Thank you so much for going through this to find a solution. Your suggestion fixed the issue!

Issue fix in commit: 8d9f7ad
